apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: mg44rynqt-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mg44rynqt-nodejs 
  name: mg44rynqt-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: mg44rynqt-nodejs 
